### ISSUE TITLE
document code deployment

### ISSUE THREAD

**Issue by zebulasampedro** [ResearchComputing/RCAMP#1]

**Comment by zebulasampedro** [comment]
The official [Django Deployment Guide](https://docs.djangoproject.com/en/1.8/howto/deployment/).

**Comment by anderbubble** [comment]
This is likely meant to target a new, rcops-managed web server, to-be-deployed.

**Comment by anderbubble** [comment]
https://wiki.rc.colorado.edu/rcops/index.php/RCAMP

https://gitlab.rc.int.colorado.edu/rc-ops/curc-puppet/blob/development/modules/curc/manifests/roles/rcamp.pp
