### ISSUE TITLE
document NSF reporting requirements

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#11]
We need to make sure we're tracking sufficient data to fulfill NSF reporting requirements. To that end, we should document (either in the repo or on the wiki) our NSF reporting requirements to inform future development.

**Comment by pruprecht** [comment]
Also need to include info on CU reporting requirements.  Eg, to answer questions from department or colleges about how many of their users are supported and in what ways.

**Comment by pruprecht** [comment]
https://wiki.rc.colorado.edu/rcops/index.php/Reporting_requirements
