### ISSUE TITLE
Allocations can be determined to be CSU or non-CSU in the allocation api

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#122]

**Comment by zebulasampedro** [comment]
Allocations in the API expose a link to the related project, which also contains information about the organization.

**Comment by anderbubble** [comment]
Observed at https://rcamp2.rc.int.colorado.edu/api/allocations/.

<img width="741" alt="screen shot 2016-10-10 at 4 32 06 pm" src="https://cloud.githubusercontent.com/assets/350294/19253261/1de7c412-8f07-11e6-9710-471c0800f52f.png">
