### ISSUE TITLE
fix django administrative email

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#135]
Django is supposed to email tracebacks when there's an internal server error, but those emails aren't going out.

**Comment by zebulasampedro** [comment]
@anderbubble Error emails are only generated and sent when `DEBUG` is set to `False`. It is currently set to `True` on both hosts.

**Comment by anderbubble** [comment]
@zebulasampedro It's set to True because I wasn't getting the tracebacks in email when it was set to False.

**Comment by anderbubble** [comment]
I'm still not getting administrative email from camp when an error is encountered.

**Comment by zebulasampedro** [comment]
I submitted an issue in GitLab that summarizes the changes I made to the logging setup. Mail and file logging now work. _Simultaneously!_

**Comment by anderbubble** [comment]
I'm going to leave this open until I push the change out to production.

**Comment by anderbubble** [comment]
Fixed! Turns out the bulk of the problem was that Django was sending email as root@localhost.
