### ISSUE TITLE
manage project managers and collaborators as Python lists in form input without serializing through str

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#136]

**Comment by zebulasampedro** [comment]
@anderbubble https://docs.python.org/2/library/ast.html#ast.literal_eval

`ast.literal_eval` isn't able to evaluate arbitrary expressions (only Python literals), nor is it eagerly evaluated like `eval`. It is considered safe for untrusted sources.

**Comment by anderbubble** [comment]
@zebulasampedro Yeah, I read about that a bit last night and backed down from my original red-eyed reaction. :) But if I'm following the code correctly, the only reason you need to use ast is because you're already passing a python `list` through `str()` at some point earlier. The better thing to do would be to find where the list is being erroneously converted to a `str`, and just leave it as a list.

What you've pointed out, though, is why I've tagged it as __future__, rather than production migration, btw.

**Comment by zebulasampedro** [comment]
@anderbubble That isn't true. The python list isn't being erroneously passed through `str()`, it is being passed in an HTTP request so it gets stringified in both directions. The form field is what is meant to deserialize that data back into a Python type.

**Comment by anderbubble** [comment]
@zebulasampedro the widget renders as a `<select multiple="multiple">`. This comes into Python as a list of strings, being the values of the selected `<option>`s. This list is getting serialized to a string by `ProjectForm` by virtue of `ModelForm`, because it's, by default, using a `CharField` to read in `ProjectForm.managers` and `ProjectForm.collaborators`. You're replacing the displayed widget in `ProjectForm.__init__`, but it's still getting passed through the `CharField` eventually, which is when the `List` produced by `FilteredSelectMultiple` gets converted to a string. A better option would be to use a `ModelMultipleChoiceField`, which should pass the resultant list through as a list in `cleaned_data`.

https://docs.djangoproject.com/en/1.10/topics/forms/modelforms/

**Comment by zebulasampedro** [comment]
@anderbubble The admin widget _was_ originally designed for the ModelMultipleChoiceField, but that field type cannot be used for an ldapdb field, since ldapdb does not (and cannot) support foreign keys. That is why a ListField is being used instead.

**Comment by anderbubble** [comment]
@zebulasampedro I'm not talking about the model field; I'm talking about the form field. Since `lib.fields.ListField` is based on `django.db.models.TextField`, `django.forms.ModelForm` is using a `django.forms.CharField` to parse the form input by default. But no-matter how the model is represented and serialized, it's more appropriate to use a `django.forms.ModelMultipleChoiceField` or `django.forms.MultipleChoiceField` in the form, so the form doesn't serialize the list to a string only to require you to re-parse it back into a list again.

Again, though, this is an issue for the future. I found this because of #129, which is the higher-priority issue / actual bug. This is an implementation detail.

**Comment by zebulasampedro** [comment]
@anderbubble What you're proposing is not the most appropriate solution, as there are elements of the client-side implementation that are being overlooked. The real issue is that the empty string condition that caused #129 is not yet being handled. This `ast` issue is invalid.

**Comment by anderbubble** [comment]
I am not convinced that this issue is invalid; but I'm happy to hear what client-side implementation issues I'm overlooking.

Do feel free to ignore this for now, though, in favor of #129.
