### ISSUE TITLE
reconfigure csu user account requests to generate accounts with homedir /home/${uid}@colostate.edu

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#153]
The previous definition of csu homedirs was to namespace at `/home/csu/${uid}`, but since the system locally uses `${uid}@colostate.edu` as the effective uid, it's simpler, and less surprising, to use `/home/${uid}@colostate.edu` as the homedir, too.

**Comment by zebulasampedro** [comment]
@anderbubble Does this change affect CU users as well? Am I correct in assuming that `/home/ucb/${uid}` needs to be transformed into `/home/${uid}@colorado.edu`?

**Comment by anderbubble** [comment]
CSU users aren't doing /home/ucb/${uid} today, are they? If so, they should be /home/${uid} (no @colorado.edu suffix)

**Comment by anderbubble** [comment]
https://github.com/ResearchComputing/RCAMP/blob/master/rcamp/accounts/models.py#L193

Wow. I didn't realize that. I probably asked for it; but let's not do that.

So, to be clear:

* csu users: `/home/${uid}@colostate.edu`
* cub users: `/home/${uid}`

**Comment by zebulasampedro** [comment]
#18 mentions it. I will move to the new schema above when I fix this issue.
