### ISSUE TITLE
re-unify organizationally-distinct users and groups in a single ou structure

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#155]
In an attempt to prevent namespace collisions, we used `ou={csu,ucb},ou={people,groups}` for csu and ucb users and groups, respectively. However, since this always gets flattened out in POSIX anyway, we namespace *there* by having sssd append an `@colostate.edu` suffix to csu entities.

It'd be easier to just namespace uid in ldap and not have multiple ldap trees.

Re-unify in the code back to a single ldap tree for all organizations, and then update the deployed configuration to use the root `ou={people,groups}` RDNs.

**Comment by zebulasampedro** [comment]
@anderbubble I'm assigning this to you initially to solicit stories and requirements.

**Comment by anderbubble** [comment]
I've been working on provisioning an XSEDE user by hand like this. Some observations:

* sssd really doesn't seem to like having the @xsede.org domain suffix in the username. It wants to manage the suffix itself.
* we can use organizationName / o to identify an organization for an iNetOrgPerson (which our accounts are); but you can't add organizationName to a posixGroup class as it exists. We'd need to create an aux objectclass that would manage organizationName on a posixGroup if we wanted to do that. (And we do have to support per-domain groups, since sssd won't allow users to be members of groups across domains.)

**Comment by anderbubble** [comment]
1. I've been getting distressing radio-silence from red hat on my [bug report](https://access.redhat.com/support/cases/#/case/01949378).
2. It seems that `re_expression` support in multi-domain configurations is totally broken.
3. Even if Red Hat does fix this, it likely wouldn't be backported to 6.x hosts

With this, I'm afraid we need to abandon our plans to move uid/gid suffixes into LDAP, which would be a practical requirement for this unification.

Thoughts?

**Comment by zebulasampedro** [comment]
I will reprioritize this next sprint to focus on resolving issues with ou separation support in RCAMP.
