### ISSUE TITLE
update the RCAMP terms and conditions with info on citing Summit

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#158]
from Pete:

>If you think it's important to include the NSF MRI grant numbers for Summit in the "Terms and Conditions" on the portal, they are:
>
> (MRI Award Nos. ACI-1532235 and ACI-1532236)
> 
> Presumably these are desirable to put in there since the Janus T&C had it.

**Comment by zebulasampedro** [comment]
These changes were included in #182.
