### ISSUE TITLE
require that users acknowledge their contact address

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#16]
At this point I don't think we should allow users to specify an arbitrary contact address--we should just user what's in CU LDAP or XSEDE--but we should require that the user acknowledge the address we'll be using. I imagine a simple checkbox next to the email address that must be ticked to proceed with the account request, almost exactly like a terms and conditions acknowledgement box.

**Comment by zebulasampedro** [comment]
@anderbubble @knuths Just came across this issue and I'd like to propose an idea about how to improve our user workflow:

We could move to the standard email verification process during account request, and then the verification link we send to users via email could take them to a _Next Steps_ page, where we can ask them questions about what resources they'd like to use, etc., and guide them from there, reducing the volume of email and hands-on interaction on our part.

This approach would be much more similar to the standard web account request process as well.

**Comment by knuths** [comment]
@zebulasampedro @anderbubble are you suggesting that instead of what we originally talked about (basically all the check boxes) that the checkboxes would be on a separate page?  I like the idea.  I think it might reduce confusion.
