### ISSUE TITLE
account creation should put UCB users into a "ucb" group

### ISSUE THREAD

**Issue by pruprecht** [ResearchComputing/RCAMP#163]
In order to allow only UCB users to access UCB-licensed software, I think we'll need a "ucb" POSIX group in LDAP and all UCB users (but not CSU, XSEDE, etc) should be members of it.

**Comment by anderbubble** [comment]
This looks good; though `settings.py` should probably just define `LICENSE_GROUPS = {}`, and then the code should be resilient to there being no `ucb` key in the dict.
