### ISSUE TITLE
Make the general account access request more visible / obvious

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#165]
Maybe a note on the bottom-right login link, then a bit more set apart / defined in the project page / after login.

**Comment by anderbubble** [comment]
From @jafrahm:

```
When you are logged in it says:

Manage your projects
The Project Management Page allows you to review, edit, and request time against your projects.

We should indicate that the link also directs you to the mailto link for General access.

When logged in it seems like this page is a doubling of the other page however but maybe that is due to there being only one choice currently. I'd address this by putting the mailto: for General access on this page as well as the link to the Project and Allocation management interfaces.
```

**Comment by anderbubble** [comment]
@jafrahm I think one of the things you were asking for was to copy the general account request mailto: to the first login landing page, rather than just in the project management list. Populating that mailto: well meant adding some code to the backend to pass the necessary information to the frontend. I can do that at that index page as well; but I wanted to check to see if you think what's been added now, so I might avoid the duplicated backend code. :)

(I'm attaching screenshots here since they won't be pushed to production yet.)

<img width="688" alt="screen shot 2017-02-16 at 3 37 24 pm" src="https://cloud.githubusercontent.com/assets/350294/23044649/5d4d32c4-f45e-11e6-8c4f-a1e877085784.png">

<img width="780" alt="screen shot 2017-02-16 at 3 37 38 pm" src="https://cloud.githubusercontent.com/assets/350294/23044657/5f9d0068-f45e-11e6-9b72-31306c096537.png">

<img width="801" alt="screen shot 2017-02-16 at 3 37 50 pm" src="https://cloud.githubusercontent.com/assets/350294/23044659/626cca58-f45e-11e6-82b4-2af25db22a41.png">

**Comment by jafrahm** [comment]
I'm OK with having to jump off that landing page, it seems unnecessary from a user perspective but it's a small thing.   It seems like a page with one button that says "Now press this button" but it's OK for now.  Maybe we can add other options to the landing page eventually.

It would be good to wordsmith the front page a bit so a user who has not read up on the jargon can understand which choice to make.  I am not coming up with anything good.
If you were just a new user wanting to try some Python would you think to click on "Manage your projects"?  A lot of users will assume some sort of basic access is automatic.  Maybe:
"Start using Compute Resources or Manage your Projects"  
[I do not like it but am kinda stuck]

Regarding the Project Management page, does it fork to a mailto: for UCB or CSU based on the user's attributes?

We should call out the time limit for General access too so people hesitate to start the clock if they do not need to run yet.  Some of the Failure to Thrive users were getting Startups  as part of their onboarding and then realizing they did not need RC resources for another year or more.  We had 390 unused Startups which means about 60% of all Startups were never used.

We could put some of the detail into the Mailto: body to avoid overloading the page.
How about:

"The Project Management page allows you to define and manage Projects and request Compute Time allocations and to request limited access to the Compute via UCB-General or CSU-General access"

"UCB faculty, staff and students may Contact Us to request one-time limited access to UCB-General for lower-priority access to the compute without a Project/Compute time allocation.  Please note that visitors and external collaborators need to be on a Project supervised by UCB Faculty/PI.
Usage must be in compliance with the IT Resources Acceptable Use Policy:
http://www.colorado.edu/policies/acceptable-use-cu-boulders-it-resources

Then in the Mailto: message body we put: 
"Please add me (username) to UCB-General for one-time, up to one year limited access to the Compute from the date of approval.  I will use this access to [insert reason or activity here].  

I certify that I am a UCB faculty, staff or student in good standing and will use the resources in compliance with the  CU Boulder IT Resources Acceptable Usage Policy.
