### ISSUE TITLE
simplify ldap testing process / framework

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#171]
My biggest barrier-to-entry for contributing to RCAMP is writing LDAP-facing tests. I'd love it if this were simplified.

**Comment by zebulasampedro** [comment]
A major source of complexity and test code volume comes from the mock LDAP server that gets instantiated for each test case. Beyond being difficult to read, this mock has also proved limiting as it is not immediately possible to run multiple mock servers within the same test case. The initial motivation for the mock LDAP server was to allow for integration testing of LDAP-dependent components. Given the predominance of LDAP-dependent code in RCAMP though, this slowly became unmaintainable.

To simplify the testing framework, and also to allow for the client to be put under test, the test suite will be refactored as such:
* **Add functional tests.** Functional tests backed by selenium, the Django framework's `StaticLiveServerTestCase`, and the rc-test-ldap Docker image (https://hub.docker.com/r/researchcomputing/rc-test-ldap/) will be added. This testing pattern will replace all tests that cover CBVs, view functions, and admin forms.
* **Deprecate mock LDAP server for unit tests.** Unit tests will now be fully isolated by mocking out LDAP dependencies at the object manager or queryset level with `MagicMock`. This eliminates the need for the inconvenient mock server, and promotes DAMP unit tests.
* **Provide common testing utilities in `lib`.** This will include functional test classes, auth backends for testing, etc. These utilities will reduce boilerplate code without compromising the DAMPness of the test suite.
