### ISSUE TITLE
Population of mailto: headers for general account request

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#173]
From @jafrahm:

> Jonathon said something about building out that mailto: to load the Subject, etc. it'd be interesting to know what can be achieved there to get consistency from the results.

**Comment by jafrahm** [comment]
Naturally a static mailto: is easy enough but it'd be great to leverage something like those {{ mustache_variables }} to nuance the subject line and perhaps the body as well.

If static we can put in some message body to elucidate the expected response:
<a href="mailto:rc-help@colorado.edu?subject=Summit General Compute Request&body=Please add me to Summit General for up to one year, I have included below a brief abstract of my intended use of Summit.">Email your Summit General Compute Request</a>

**Comment by anderbubble** [comment]
Copied from #165 from @jafrahm 

> Regarding the Project Management page, does it fork to a mailto: for UCB or CSU based on the user's attributes?

Yes, it should display a request for `ucb-general` or `csu-general` based on your organization. That's why there's extra code in the PR: to provide the necessary variables to direct it to the correct place.

> Then in the Mailto: message body we put:
>> "Please add me (username) to UCB-General for one-time, up to one year limited access to the Compute from the date of approval. I will use this access to [insert reason or activity here].
>>
>> I certify that I am a UCB faculty, staff or student in good standing and will use the resources in compliance with the CU Boulder IT Resources Acceptable Usage Policy.

Will do.
