### ISSUE TITLE
Account request form should notify user if they already have an account

### ISSUE THREAD

**Issue by pruprecht** [ResearchComputing/RCAMP#174]
After a user submits the account request form, it should check whether an RC account already exists for that user.  If not, continue as usual.  If so, present a page informing the user that their account already exists and asking them to email rc-help for further help.

**Comment by anderbubble** [comment]
@zebulasampedro could you add a message to the exception?

> Please contact rc-help@colorado.edu if you need help accessing this account.

**Comment by zebulasampedro** [comment]
@anderbubble A similar message with a mailto link already exists.

<img width="1149" alt="screen shot 2017-05-10 at 4 24 25 pm" src="https://cloud.githubusercontent.com/assets/2158268/25923924/36a7e6fc-359d-11e7-9924-8fab8513ba02.png">
