### ISSUE TITLE
Behavior of {{ account.username }} for CSU users

### ISSUE THREAD

**Issue by jafrahm** [ResearchComputing/RCAMP#177]
From the cases we are getting and email subject lines I see quoted it appears that  {{ account.username }} for CSU usernames does not contain .colostate.edu and this the emailed instructions do not work as they suggest the wrong username.  The issue is getting correct instructions to CSU users ideally both in the subject line and message body of the auto-email.  Consistency of the username between the subject and body is important in case of tl; dr.

**Comment by jafrahm** [comment]
I can imagine if we need to address this quickly maybe we can assign a {{ variable }} to the account username "suffix", which is empty or unset if the user is UCB and ".colostate.edu" for CSU (and so on) then just expand both these variables in a row in the communications.

**Comment by anderbubble** [comment]
@jafrahm presumably you're talking about the emails that are being generated as a result of account created? If so, the quickest solution is probably just to hard-code `@colostate.edu` suffixes in the email for now, as they should already be branching based on whether it's a csu account or not. (That is, a different email body should be being sent out to csu users.)

The final solution for this is to actually include the `@colostate.edu` suffix in the uid field in ldap, and stop appending it with sssd; but that might come a bit later.

**Comment by jafrahm** [comment]
Yes if the branching is working we can hard-code the username in the CSU message body but perhaps not the subject, so that'd wait until the suffix is in the {{ account.username }} for CSU, etc.

**Comment by anderbubble** [comment]
This was being handled correctly in the body; but the subject line didn't have the colostate.edu suffix. To simplify this difference, I've split the `AccountCreated` mailer into explicit `CSU` and `UCB` variants, and customized each appropriately. Let me know if there's any trouble.
