### ISSUE TITLE
terms and policies button doesn't do anything [safari]

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#180]
It works at `accounts/account-request/create`; but the same (or very similar) button appears on all pages, and is unresponsive.

Need to fix at

* <del>url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),</del>
* <del>url(r'^login', auth_views.login, {'template_name':'login.html'}),</del>
* <del>url(r'^logout', auth_views.logout, {'template_name':'logout.html'}),</del>

**Comment by pruprecht** [comment]
I think this is a recurrence of my previously-reported issue; if not let me know and I can open a new one.

The "Terms and Conditions" button doesn't do anything on
https://rcamp.rc.colorado.edu/projects/list
https://rcamp.rc.colorado.edu/projects/create

I'm using firefox on MacOS.
