### ISSUE TITLE
New CU accounts aren't using CU uidNumber

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#197]
When a CU user creates an RC account, the RC account is meant to be created with a uidNumber and gidNumber that matches the CU uidNumber value. This apparently isn't happening in the current version of RCAMP; but it did happen in its predecessor.

This functionality is required should we ever want to start using CU LDAP more directly (and we do want to do that).

## Examples

```
[root@login01 ~]# ldapsearch -LLL -x   -H ldap://ad.colorado.edu:389   -b 'ou=people,dc=ad,dc=colorado,dc=edu'   -D 'AD\joan5896' -W   '(sAMAccountName=joan5896)' uidNumber
Enter LDAP Password: 
dn: CN=joan5896,OU=People,DC=ad,DC=colorado,DC=edu
uidNumber: 416810

[root@login01 ~]# id joan5896
uid=416810(joan5896) gid=416810(joan5896pgrp) groups=416810(joan5896pgrp),1000000(rcopspgrp),1000505(ics-auto_analysispgrp),1101293(kari0458grp),1000509(ics-archivepgrp),1100098(ruprechgrp),1101822(joan5896grp)
```

```
[root@login01 ~]# ldapsearch -LLL -x   -H ldap://ad.colorado.edu:389   -b 'ou=people,dc=ad,dc=colorado,dc=edu'   -D 'AD\joan5896' -W   '(sAMAccountName=barnhark)' uidNumber
Enter LDAP Password: 
dn: CN=barnhark,OU=People,DC=ad,DC=colorado,DC=edu
uidNumber: 127375

[root@login01 ~]# id barnhark
uid=127375(barnhark) gid=127375(barnharkpgrp) groups=127375(barnharkpgrp),1101862(barnharkgrp)
```

**Comment by anderbubble** [comment]
This is relatively urgent, as any CU account that gets created in RC ldap with an unmatched uidNumber represents an annoying and potentially arduous filesystem cleanup to swap the new uidNumber for the CU uidNumber at some point.

**Comment by zebulasampedro** [comment]
@anderbubble In the case of a UID number conflict between the RC LDAP and the CU LDAP, which one takes precedence? How should this be handled?
