### ISSUE TITLE
Mail Notifier Fields for Allocation Requests 

### ISSUE THREAD

**Issue by jafrahm** [ResearchComputing/RCAMP#199]
As per:
https://wiki.rc.colorado.edu/rcops/index.php/RCAMP

There is no Mail Notifier Fields for Allocation Requests for the requester email and PI email.
I use these fields to work with the requester and notify the PI for the approval process.  They may also be needed for a confirmation email direct from RCAMP

**Comment by anderbubble** [comment]
@zebulasampedro is this an actual missing field or just a documentation issue?

**Comment by zebulasampedro** [comment]
#214 adds the requester's Account to the event context.

@jafrahm In the mailer documentation, when the _Type_ is either `project` or `account` it indicates that the attribute/variable in question refers to the Project type or the Account type and all attributes of those objects can be used.

For instance:
```
allocation_request.project.pi_emails
```
