### ISSUE TITLE
Uploaded proposal document not found

### ISSUE THREAD

**Issue by pruprecht** [ResearchComputing/RCAMP#200]
In https://rcamp.rc.colorado.edu/projects/list/12/allocationrequests/3/ , the link to the uploaded proposal document returns "Oops, the requested page doesn't exist".

**Comment by pruprecht** [comment]
The link is to https://rcamp.rc.colorado.edu/media/proposals/2017/04/10/rc_handout2017.docx

**Comment by zebulasampedro** [comment]
@anderbubble Is nginx on `rcamp1` configured to host the media files? I looked over the config and didn't see anything.

**Comment by anderbubble** [comment]
This was a server configuration issue, and has been fixed.
