### ISSUE TITLE
remove incrementation arrow in allocation request page

### ISSUE THREAD

**Issue by pruprecht** [ResearchComputing/RCAMP#202]
In https://rcamp.rc.colorado.edu/projects/list/12/allocationrequests/create , the CPU time requested field shouldn't have the incrementation arrow (it doesn't make sense to up-arrow 50K times for a small request.)  This is a very minor issue.

**Comment by anderbubble** [comment]
I don't see a standardized way to disable this across browsers.

https://stackoverflow.com/questions/3790935/can-i-hide-the-html5-number-input-s-spin-box

I'm going to defer this for now to see if we can find a way to do this with a later version of bootstrap.
