### ISSUE TITLE
remove bash variable syntax from account request page

### ISSUE THREAD

**Issue by pruprecht** [ResearchComputing/RCAMP#204]
There is user confusion regarding the syntax "${}" syntax on https://rcamp.rc.colorado.edu/accounts/account-request/create/general .  Particularly the ${csu_password},${duo_otp} or ${csu_password},push information.

Please change to match the documentation CSU uses when telling how to use Duo auth, which has the ${} removed, ie, "csu_password,duo_key or csu_password,push"

**Comment by pruprecht** [comment]
This request also affects https://rcamp.rc.colorado.edu/accounts/account-request/create/project

**Comment by anderbubble** [comment]
See PR #222
