### ISSUE TITLE
Project/allocation-related pages should link to RC user guide allocation page

### ISSUE THREAD

**Issue by pruprecht** [ResearchComputing/RCAMP#206]
Updated project and allocation documentation is now available at https://www.rc.colorado.edu/support/user-guide/allocations.html .  Please change links ("Questions about project creation?") on project/allocation-related RCAMP pages to point to it instead of the "Getting Started" URL.

Examples of where this is needed include:

https://rcamp.rc.colorado.edu/projects/create
https://rcamp.rc.colorado.edu/projects/list/12/allocationrequests/create

**Comment by anderbubble** [comment]
See #221
