### ISSUE TITLE
Allow users to associate other people with their projects

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#22]
I see this as a list of strings, so random names and email addresses can be included; but we could later infer allocation membership by parsing these strings.

**Comment by zebulasampedro** [comment]
If we require that they provide a list of e-mails, we could later send account request links to the emails provided.

**Comment by anderbubble** [comment]
> If we require that they provide a list of e-mails

Requiring an email address is not onerous, fair enough, and I'd be totally ok with this implementation; but I think even better would be if we *detect* the presence of an email address in an otherwise freetext input, and enable/disable a "send an account invitation" button dynamically based on that.

**Comment by anderbubble** [comment]
review pending #76

**Comment by anderbubble** [comment]
As implemented, it looks like this doesn't support arbitrary people being associated with a project, which *is* what is described as the desired feature. In the interest of minimum-viable, though, I'm going to create a new issue to track that additional enhancement for __future__, and decide that this is sufficient for now.
