### ISSUE TITLE
Add help text to Project Creation page

### ISSUE THREAD

**Issue by pruprecht** [ResearchComputing/RCAMP#229]
On https://portals.rc.colorado.edu/projects/create please add documentation text for the "Description" field.  This could be a "more info" button, a text block above the Description box, or type-overable pre-fill text within the Description box.

The help info should contain the following items:

The Project Description should include:
-Concise description of the research project and its significance (3-5 sentences)
-Estimated Project timeframe/duration (normally minimum 1 year, maximum 5 years)
-Concise description of the related computational work (3-5 sentences)
-Goals (typically degrees, publications, presentations, data products)
-Grants that support this project, specifically grants that are directly related to work performed on RC resources.  If possible, please include the name of the funding agency, the grant number, and its dollar value.
-General description of the data storage, sharing and management for the project, and beyond if applicable (minimum 2-3 sentences).

**Comment by zebulasampedro** [comment]
@pruprecht How does this look to you?

![screen shot 2017-08-10 at 09 41 53](https://user-images.githubusercontent.com/2158268/29178928-367863f4-7db0-11e7-8cd6-a66daf19740e.png)

**Comment by pruprecht** [comment]
The proposed layout looks great, thanks.
