### ISSUE TITLE
RCAMP uses user name as supplied by user

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#231]
It appears that RCAMP, during account creation, uses the username as supplied by the user rather than re-querying it from upstream LDAP. This shouldn't be too big a deal, since we only use it after they've successfully authenticated; but it does mean that our copy of the username might have different capitalization than upstream.

**Comment by zebulasampedro** [comment]
RCAMP uses data queried from upstream when creating local users, and it appears that upstream is where the casing problem originates. See #232.
