### ISSUE TITLE
Upgrade to newest LTS release of Django

### ISSUE THREAD

**Issue by zebulasampedro** [ResearchComputing/RCAMP#251]
Django 1.8.5 will sunset April 2018. RCAMP needs to be upgraded to v1.11 LTS prior to that date.

**Comment by AaronTHolt** [comment]
https://docs.djangoproject.com/en/1.11/releases/1.11/#backwards-incompatible-changes-in-1-11

**Comment by AaronTHolt** [comment]
Django is at 1.11.
