### ISSUE TITLE
Allocation publication (REST api)

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#27]
Create a rest api for querying allocations from RCAMP, and create a script that consumes this api and configures slurm appropriately.

The api should allow for a low-bandwidth query of "last updated" value that can be polled more frequently, without having to dump all of the active allocations each poll.

**Comment by zebulasampedro** [comment]
> ...and create a script that consumes this api and configures slurm appropriately.

Is the API consumer also within the RCAMP scope, or should this be broken out into a separate issue?

**Comment by anderbubble** [comment]
> Is the API consumer also within the RCAMP scope, or should this be broken out into a separate issue?

It's probably reasonable to separate them. I'll do that.

**Comment by anderbubble** [comment]
![screen shot 2016-09-16 at 10 33 54 am](https://cloud.githubusercontent.com/assets/350294/18593546/1f6f5a46-7bf9-11e6-9198-4e1db455677c.png)
