### ISSUE TITLE
deploy and document new web server for rcamp

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#3]

**Comment by anderbubble** [comment]
Jon: Zeb says that you spun up an rcamp server yesterday, so I'm assigning this to you for now; but feel free to send it back if you prefer.

**Comment by pruprecht** [comment]
Note that running our own web server commits us to keeping it fully patched, updated, secured, etc according to OIT guidelines.  Any non-SIS public facing servers are likely to receive increased scrutiny by the new ITSO staff.  I'm not at all saying this to discourage the idea of using our own web server; I'm in favor of it.  Rather, just a heads up that we need to keep OS and software stack updatability in mind throughout this project.  Someone will need to be in charge of keeping things updated.

 -Pete

**Comment by loptienj** [comment]
rcamp.rc.int.colorado.edu has been deployed. Zeb didn't say what all he needs on it so LDAP is the only thing on it right now.

**Comment by anderbubble** [comment]
https://wiki.rc.colorado.edu/rcops/index.php/RCAMP
