### ISSUE TITLE
allow users to view a list of their associated projects

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#32]
Distinguish between projects that the user "owns" (which can be edited) and projects that the user is simply affiliated with (which they cannot edit).

**Comment by anderbubble** [comment]
It looks like the projects list shows *all* projects, and doesn't appear to distinguish how the user is affiliated with the project.

**Comment by anderbubble** [comment]
I'm really unclear what's going on on the project list page.

<img width="1497" alt="screen shot 2016-09-10 at 12 32 48 am" src="https://cloud.githubusercontent.com/assets/350294/18408481/240aa642-76ee-11e6-9e23-6e7af28f65e6.png">

There's a project list at the top, inline with the "create a new project" link, but it only shows one of my projects, not both of them.

<img width="1497" alt="screen shot 2016-09-10 at 12 33 35 am" src="https://cloud.githubusercontent.com/assets/350294/18408487/3a35c172-76ee-11e6-84db-fb5183d9906a.png">

Meanwhile, there's the project detail thing at the bottom, but it appears to just show the same project list with the same level of detail.

**Comment by zebulasampedro** [comment]
The issue reported by @anderbubble was caused by having been logged in as the admin user, instead of the intended user.
