### ISSUE TITLE
remove all mention of Janus from RCAMP templates

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#36]
RCAMP should not refer to "Janus" in general, except when referring to the specific resource (e.g., in an allocation request or account request interest indicator).

For example, the current header reads, "Request an account on the Janus supercomputer at the University of Colorado Boulder." It should be "Request a Research Computing account."

**Comment by zebulasampedro** [comment]
Blocked pending approval of new Terms & Conditions.

**Comment by anderbubble** [comment]
Fixed by #87
