### ISSUE TITLE
pi permission / designation

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#6]
We should have a mechanism to indicate if a user can be the PI of a Research Project.

Potential implementation patterns:

* general-purpose role field
* unix group membership
* special-purpose boolean

**Comment by zebulasampedro** [comment]
My preference would be to assign PI status via unix group membership. That fits the current RCAMP data model quite well, and abides by the tenet that we should duplicate as little data as possible.

**Comment by anderbubble** [comment]
There are annoying technical NFS-related reasons to want to limit the number of unix groups a user is a member of.

How easy would it be to key operational parameters (e.g., the right to define a project) off of the unix group in the RC directory? (I expect trivial, but just want to be sure.)
