### ISSUE TITLE
Project creation

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#66]
## Narrative

1. The user logs into RCAMP.
2. The user clicks the ‘Create a Project’ link.
3. The user fills out the Project Creation form.
4. The user clicks the “Create project” button. A project is immediately created, and can be viewed by the user that created it.
5. A notification email is sent to each PI listed on the project.

**Comment by anderbubble** [comment]
Account creation doesn't currently require login.

**Comment by zebulasampedro** [comment]
cb5c87a2acf4c3cb74bbab73339916ad2618ff2b Added auth to the project creation page.
