### ISSUE TITLE
account review and disabling

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#7]
> We should also be doing something with visitor/collaborator accounts to review/disable them but we can infer that from a role and a creation date, if the role is unambiguous.  Maybe we need to link visitors to sponsors in the data set so we can automate the sending of visitor renewal requests.  We could do this at the Project level but I am not sure if we will end up with a significant number of active users (using storage or network or shell) who are not part of an active project.

**Comment by jafrahm** [comment]
Is there a procedure at present, manual if necessary, to disable users?  Will disabling them in MUMP work?

**Comment by anderbubble** [comment]
Right now, I think the only viable option is to change the user's shell to `nologin`.

In the past, I've seen an "authorized users" group or a "disabled users" group used that's consulted at login. We don't have something like this today, but it'd be an option.

Worth noting: I *think* the way MUMP did account disabling was to modify `curcRadiusName`. `curcRadiusUser` isn't part of the new LDAP directory; but I also think that this method of disabling users wouldn't have worked even before the migration for Duo users, as I think it only interfered with a user's ability to do VASCO authentication.

Here's some potential mechanisms for handling account authorization in the future. (Other suggestions welcome, though.)

* disable accounts by changing the shell to `nologin`
* define a `curcdisabled` (or similar) unix group and add people to it (or invert this to an authorization group)
* maintain a disabled-users `pam_access` file and distribute that to login nodes (or invert this to an authorization list)
