### ISSUE TITLE
Recent Actions continues to provide a link to objects that don't exist

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#71]
I created testgroup, which now shows up in Recent Actions; but I deleted testgroup out-of-band, so the link goes to a 404. Probably the best thing is to just populate a 404 page, as I'm just getting the django debug output now.

**Comment by zebulasampedro** [comment]
You're getting a stacktrace because the `DEBUG` setting is `True`. Once RCAMP is in production, that setting will be set to `False` and you will see a regular 404/500 page.
