### ISSUE TITLE
/logout appears to not actually log you out

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#72]
after I navigate to /logout but then to /projects/create, I appear to still be logged in.

**Comment by anderbubble** [comment]
I see now that project creation lists me simply because I exist; not because it thinks I'm logged in. It seems that accessing the project creation interface simply doesn't require login; which is a different bug.

**Comment by anderbubble** [comment]
I'm back to thinking that /logout doesn't actually log you out; I can still list projects with /projects/list even after /logout.

**Comment by zebulasampedro** [comment]
The appearance of not being logged out was caused by #76. The logout functionality is verified and intact.
