### ISSUE TITLE
Restructure Project/Allocations to maintain SlurmDB integrity

### ISSUE THREAD

**Issue by zebulasampedro** [ResearchComputing/RCAMP#79]
Project names (which become Slurm account names), need to be moved to Allocations. Additionally, a constraint must be added that Allocations cannot be renamed or deleted, and projects that are related to created allocations must also not be deleted.

**Comment by anderbubble** [comment]
I suggest that projects still have a project name, but that allocations have a separate (non-unique?) allocation name, and that allocation names are user-immutable.

**Comment by zebulasampedro** [comment]
This issue is most effectively solved with documentation.
