### ISSUE TITLE
handle account organization / affiliation distinctions

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#8]
> Handle XCEDE and CSU users with new username schema

Each set of users should go in a distinct OU in ldap. To that end, we'll need an org->OU map.

**Comment by zebulasampedro** [comment]
The following are the ous the portal will be expecting: "cu", "csu", "xsede", and "internal". The ous themselves are malleable from the portal's perspective however, if there is a problem with the above list.

**Comment by anderbubble** [comment]
Added ucb, csu, xsede, and internal. Copied existing non-ncar users into ucb (will clean up later). Don't forget about NCAR ou.
