### ISSUE TITLE
User can request access to scavenger project

### ISSUE THREAD

**Issue by zebulasampedro** [ResearchComputing/RCAMP#85]
A mailto link should be displayed to the user that allows them to request access to the scavenger project. Once granted, the scavenger project should be displayed in their projects page.

**Comment by anderbubble** [comment]
Seen implemented with mailto.

![screen shot 2016-09-15 at 4 16 21 pm](https://cloud.githubusercontent.com/assets/350294/18569429/c225ad70-7b5f-11e6-9567-634b0cab0b31.png)
