### ISSUE TITLE
account requests aren't generating email

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#91]
Not sure where the problem is; but the mail server isn't seeing any mail coming in, so I suspect it's the app.

**Comment by anderbubble** [comment]
For the record, I *can* ping the mail server.

```EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.rc.int.colorado.edu'
EMAIL_PORT = 25
[root@rcamp2 rcamp]# ping -c 1 mail.rc.int.colorado.edu
PING mail.rc.int.colorado.edu (10.225.160.44) 56(84) bytes of data.
64 bytes from mail1.rc.int.colorado.edu (10.225.160.44): icmp_seq=1 ttl=64 time=0.708 ms

--- mail.rc.int.colorado.edu ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.708/0.708/0.708/0.000 ms```

**Comment by zebulasampedro** [comment]
@anderbubble Just validated the mailer system, and it does send email notifications for ARs. Be advised though, that email notifications must first be configured via the Mailer app admin interface.

**Comment by anderbubble** [comment]
@zebulasampedro Fair enough. Created a new documentation issue to track the fact that I have no idea how to set that up. :) #93
